# Generated by Django 4.1.5 on 2023-01-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_calories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='activitie_id',
            new_name='activity_id',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='calorie_bournout',
            new_name='calorie_burnout',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_user',
        ),
        migrations.RemoveField(
            model_name='label',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='label',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='label',
            name='updated_user',
        ),
    ]
