# Generated by Django 4.1.5 on 2023-01-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calories', '0002_rename_activitie_id_activities_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
