# Generated by Django 4.1.5 on 2023-01-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrecord',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
